#include "cpu/cpu.h"

void CPU::decode() {
    switch (CPU::opcode) {
        // case (0x00): CPU::NOP();break; // There shouldn't be a need to call this
        case (0x01): CPU::LD(R.bc, &working_word);break;
        case (0x02): CPU::LD(mem_at(R.bc), R.a);break;
        case (0x03): CPU::INC(R.bc);break;
        case (0x04): CPU::INC(R.b);break;
        case (0x05): CPU::DEC(R.b);break;
        case (0x06): CPU::LD(R.b, &working_byte);break;
        case (0x07): CPU::RLC(R.a);break;
        case (0x08): CPU::LD16SP(working_byte);break;
        case (0x09): CPU::ADD(R.bc);break;
        case (0x0a): CPU::LD(R.a, mem_at(R.bc));break;
        case (0x0b): CPU::DEC(R.bc);break;
        case (0x0c): CPU::INC(R.c);break;
        case (0x0d): CPU::DEC(R.d);break;
        case (0x0e): CPU::LD(R.c, &working_byte);break;
        case (0x0f): CPU::RRC(R.a);break;
        case (0x10): CPU::STOP();break;
        case (0x11): CPU::LD(R.de, &working_word);break;
        case (0x12): CPU::LD(mem_at(R.de), R.a);break;
        case (0x13): CPU::INC(R.de);break;
        case (0x14): CPU::INC(R.d);break;
        case (0x15): CPU::DEC(R.d);break;
        case (0x16): CPU::LD(R.d, &working_byte);break;
        case (0x17): CPU::RL(R.a);break;
        case (0x18): CPU::JR((sbyte*) &working_byte);break;
        case (0x19): CPU::ADD(R.de);break;
        case (0x1a): CPU::LD(R.a, mem_at(R.de));break;
        case (0x1b): CPU::DEC(R.de);break;
        case (0x1c): CPU::INC(R.e);break;
        case (0x1d): CPU::DEC(R.e);break;
        case (0x1e): CPU::LD(R.e, &working_byte);break;
        case (0x1f): CPU::RRC(R.a);break;
        case (0x20): CPU::JRC(CC_NZ, (sbyte*) &working_byte);break;
        case (0x21): CPU::LD(R.hl, &working_word);break;
        case (0x22): CPU::LDI(mem_at(R.hl), R.a);break;
        case (0x23): CPU::INC(R.hl);break;
        case (0x24): CPU::INC(R.h);break;
        case (0x25): CPU::DEC(R.h);break;
        case (0x26): CPU::LD(R.h, &working_byte);break;
        case (0x27): CPU::DAA();break;
        case (0x28): CPU::JRC(CC_Z, (sbyte*) &working_byte);break;
        case (0x29): CPU::ADD(R.hl);break;
        case (0x2a): CPU::LDI(R.a, mem_at(R.hl));break;
        case (0x2b): CPU::DEC(R.hl);break;
        case (0x2c): CPU::INC(R.l);break;
        case (0x2d): CPU::DEC(R.l);break;
        case (0x2e): CPU::LD(R.l, &working_byte);break;
        case (0x2f): CPU::CPL();break;
        case (0x30): CPU::JRC(CC_NC, (sbyte*) &working_byte);break;
        case (0x31): CPU::LD(R.sp, &working_word);break;
        case (0x32): CPU::LDD(mem_at(R.hl), R.a);break;
        case (0x33): CPU::INC(R.sp);break;
        case (0x34): CPU::INC(mem_at(R.hl));break;
        case (0x35): CPU::DEC(mem_at(R.hl));break;
        case (0x36): CPU::LD(mem_at(R.hl), &working_byte);break;
        case (0x37): CPU::SCF();break;
        case (0x38): CPU::JRC(CC_C, (sbyte*) &working_byte);break;
        case (0x39): CPU::ADD(R.sp);break;
        case (0x3a): CPU::LDD(R.a, mem_at(R.hl));break;
        case (0x3b): CPU::DEC(R.sp);break;
        case (0x3c): CPU::INC(R.a);break;
        case (0x3d): CPU::DEC(R.a);break;
        case (0x3e): CPU::LD(R.a, &working_byte);break;
        case (0x3f): CPU::CCF();break;
        case (0x40): CPU::LD(R.b, R.b);break;
        case (0x41): CPU::LD(R.b, R.c);break;
        case (0x42): CPU::LD(R.b, R.d);break;
        case (0x43): CPU::LD(R.b, R.e);break;
        case (0x44): CPU::LD(R.b, R.h);break;
        case (0x45): CPU::LD(R.b, R.l);break;
        case (0x46): CPU::LD(R.b, mem_at(R.hl));break;
        case (0x47): CPU::LD(R.b, R.a);break;
        case (0x48): CPU::LD(R.c, R.b);break;
        case (0x49): CPU::LD(R.c, R.c);break;
        case (0x4a): CPU::LD(R.c, R.d);break;
        case (0x4b): CPU::LD(R.c, R.e);break;
        case (0x4c): CPU::LD(R.c, R.h);break;
        case (0x4d): CPU::LD(R.c, R.l);break;
        case (0x4e): CPU::LD(R.c, mem_at(R.hl));break;
        case (0x4f): CPU::LD(R.c, R.a);break;         
        case (0x50): CPU::LD(R.d, R.b);break;
        case (0x51): CPU::LD(R.d, R.c);break;
        case (0x52): CPU::LD(R.d, R.d);break;
        case (0x53): CPU::LD(R.d, R.e);break;
        case (0x54): CPU::LD(R.d, R.h);break;
        case (0x55): CPU::LD(R.d, R.l);break;
        case (0x56): CPU::LD(R.d, mem_at(R.hl));break;
        case (0x57): CPU::LD(R.d, R.a);break;         
        case (0x58): CPU::LD(R.e, R.b);break;
        case (0x59): CPU::LD(R.e, R.c);break;
        case (0x5a): CPU::LD(R.e, R.d);break;
        case (0x5b): CPU::LD(R.e, R.e);break;
        case (0x5c): CPU::LD(R.e, R.h);break;
        case (0x5d): CPU::LD(R.e, R.l);break;
        case (0x5e): CPU::LD(R.e, mem_at(R.hl));break;
        case (0x5f): CPU::LD(R.e, R.a);break;         
        case (0x60): CPU::LD(R.h, R.b);break;
        case (0x61): CPU::LD(R.h, R.c);break;
        case (0x62): CPU::LD(R.h, R.d);break;
        case (0x63): CPU::LD(R.h, R.e);break;
        case (0x64): CPU::LD(R.h, R.h);break;
        case (0x65): CPU::LD(R.h, R.l);break;
        case (0x66): CPU::LD(R.h, mem_at(R.hl));break;
        case (0x67): CPU::LD(R.h, R.a);break;         
        case (0x68): CPU::LD(R.l, R.b);break;
        case (0x69): CPU::LD(R.l, R.c);break;
        case (0x6a): CPU::LD(R.l, R.d);break;
        case (0x6b): CPU::LD(R.l, R.e);break;
        case (0x6c): CPU::LD(R.l, R.h);break;
        case (0x6d): CPU::LD(R.l, R.l);break;
        case (0x6e): CPU::LD(R.l, mem_at(R.hl));break;
        case (0x6f): CPU::LD(R.l, R.a);break;         
        case (0x70): CPU::LD(mem_at(R.hl), R.b);break;
        case (0x71): CPU::LD(mem_at(R.hl), R.c);break;
        case (0x72): CPU::LD(mem_at(R.hl), R.d);break;
        case (0x73): CPU::LD(mem_at(R.hl), R.e);break;
        case (0x74): CPU::LD(mem_at(R.hl), R.h);break;
        case (0x75): CPU::LD(mem_at(R.hl), R.l);break;
        case (0x76): CPU::HALT();break;
        case (0x77): CPU::LD(mem_at(R.hl), R.a);break;         
        case (0x78): CPU::LD(R.a, R.b);break;
        case (0x79): CPU::LD(R.a, R.c);break;
        case (0x7a): CPU::LD(R.a, R.d);break;
        case (0x7b): CPU::LD(R.a, R.e);break;
        case (0x7c): CPU::LD(R.a, R.h);break;
        case (0x7d): CPU::LD(R.a, R.l);break;
        case (0x7e): CPU::LD(R.a, mem_at(R.hl));break;
        case (0x7f): CPU::LD(R.a, R.a);break;         
        case (0x80): CPU::ADD(R.b);break;
        case (0x81): CPU::ADD(R.c);break;
        case (0x82): CPU::ADD(R.d);break;
        case (0x83): CPU::ADD(R.e);break;
        case (0x84): CPU::ADD(R.h);break;
        case (0x85): CPU::ADD(R.l);break;
        case (0x86): CPU::ADD(mem_at(R.hl));break;
        case (0x87): CPU::ADD(R.a);break;        
        case (0x88): CPU::ADC(R.b);break;
        case (0x89): CPU::ADC(R.c);break;
        case (0x8a): CPU::ADC(R.d);break;
        case (0x8b): CPU::ADC(R.e);break;
        case (0x8c): CPU::ADC(R.h);break;
        case (0x8d): CPU::ADC(R.l);break;
        case (0x8e): CPU::ADC(mem_at(R.hl));break;
        case (0x8f): CPU::ADC(R.a);break;
        case (0x90): CPU::SUB(R.b);break;
        case (0x91): CPU::SUB(R.c);break;
        case (0x92): CPU::SUB(R.d);break;
        case (0x93): CPU::SUB(R.e);break;
        case (0x94): CPU::SUB(R.h);break;
        case (0x95): CPU::SUB(R.l);break;
        case (0x96): CPU::SUB(mem_at(R.hl));break;
        case (0x97): CPU::SUB(R.a);break;        
        case (0x98): CPU::SBC(R.b);break;
        case (0x99): CPU::SBC(R.c);break;
        case (0x9a): CPU::SBC(R.d);break;
        case (0x9b): CPU::SBC(R.e);break;
        case (0x9c): CPU::SBC(R.h);break;
        case (0x9d): CPU::SBC(R.l);break;
        case (0x9e): CPU::SBC(mem_at(R.hl));break;
        case (0x9f): CPU::SBC(R.a);break;        
        case (0xa0): CPU::AND(R.b);break;
        case (0xa1): CPU::AND(R.c);break;
        case (0xa2): CPU::AND(R.d);break;
        case (0xa3): CPU::AND(R.e);break;
        case (0xa4): CPU::AND(R.h);break;
        case (0xa5): CPU::AND(R.l);break;
        case (0xa6): CPU::AND(mem_at(R.hl));break;
        case (0xa7): CPU::AND(R.a);break;        
        case (0xa8): CPU::XOR(R.b);break;
        case (0xa9): CPU::XOR(R.c);break;
        case (0xaa): CPU::XOR(R.d);break;
        case (0xab): CPU::XOR(R.e);break;
        case (0xac): CPU::XOR(R.h);break;
        case (0xad): CPU::XOR(R.l);break;
        case (0xae): CPU::XOR(mem_at(R.hl));break;
        case (0xaf): CPU::XOR(R.a);break;        
        case (0xb0): CPU::OR(R.b);break;
        case (0xb1): CPU::OR(R.c);break;
        case (0xb2): CPU::OR(R.d);break;
        case (0xb3): CPU::OR(R.e);break;
        case (0xb4): CPU::OR(R.h);break;
        case (0xb5): CPU::OR(R.l);break;
        case (0xb6): CPU::OR(mem_at(R.hl));break;
        case (0xb7): CPU::OR(R.a);break;        
        case (0xb8): CPU::CP(R.b);break;
        case (0xb9): CPU::CP(R.c);break;
        case (0xba): CPU::CP(R.d);break;
        case (0xbb): CPU::CP(R.e);break;
        case (0xbc): CPU::CP(R.h);break;
        case (0xbd): CPU::CP(R.l);break;
        case (0xbe): CPU::CP(mem_at(R.hl));break;
        case (0xbf): CPU::CP(R.a);break;        
        case (0xc0): CPU::RETC(CC_NZ);break;
        case (0xc1): CPU::POP(R.bc);break;
        case (0xc2): CPU::JPC(CC_NZ, &working_word);break;
        case (0xc3): CPU::JP(&working_word);break;
        case (0xc4): CPU::CALLC(CC_NZ, &working_word);break;
        case (0xc5): CPU::PUSH(R.bc);break;
        case (0xc6): CPU::ADD(&working_byte);break;
        case (0xc7): CPU::RST(0x00);break;
        case (0xc8): CPU::RETC(CC_Z);break;
        case (0xc9): CPU::RET();break;
        case (0xca): CPU::JPC(CC_Z, &working_word);break;
        case (0xcc): CPU::CALLC(CC_Z, &working_word);break;
        case (0xcd): CPU::CALL(&working_word);break;
        case (0xce): CPU::ADC(&working_byte);break;
        case (0xcf): CPU::RST(0x08);break;
        case (0xd0): CPU::RETC(CC_NC);break;
        case (0xd1): CPU::POP(R.de);break;
        case (0xd2): CPU::JPC(CC_NC, &working_word);break;
        case (0xd4): CPU::CALLC(CC_NC, &working_word);break;
        case (0xd5): CPU::PUSH(R.de);break;
        case (0xd6): CPU::SUB(&working_byte);break;
        case (0xd7): CPU::RST(0x10);break;
        case (0xd8): CPU::RETC(CC_C);break;
        case (0xd9): CPU::RETI();break;
        case (0xda): CPU::JPC(CC_C, &working_word);break;
        case (0xdc): CPU::CALLC(CC_C, &working_word);break;
        case (0xde): CPU::SBC(&working_byte);break;
        case (0xdf): CPU::RST(0x18);break;
        case (0xe0): CPU::LD(mem_at(0xFF00 + working_byte), R.a);break;
        case (0xe1): CPU::POP(R.hl);break;
        case (0xe2): CPU::LD(mem_at(0xFF00 + *R.c), R.a);break;
        case (0xe5): CPU::PUSH(R.hl);break;
        case (0xe6): CPU::AND(&working_byte);break;
        case (0xe7): CPU::RST(0x20);break;
        case (0xe8): CPU::ADD_SP((sbyte*) &working_byte);break;
        case (0xe9): CPU::JP(R.hl);break;
        case (0xea): CPU::LD(mem_at(working_word), R.a);break;
        case (0xee): CPU::XOR(&working_byte);break;
        case (0xef): CPU::RST(0x28);break;
        case (0xf0): CPU::LD(R.a, mem_at(0xFF00 + working_byte));break;
        case (0xf1): CPU::POP(R.af);break;
        case (0xf2): CPU::LD(R.a, mem_at(0xFF00 + *R.c));break;
        case (0xf3): CPU::DI();break;
        case (0xf5): CPU::PUSH(R.af);break;
        case (0xf6): CPU::OR(&working_byte);break;
        case (0xf7): CPU::RST(0x30);break;
        case (0xf8): CPU::LDHL();break;
        case (0xf9): CPU::LD(R.sp, R.hl);break;
        case (0xfa): CPU::LD(R.a, mem_at(working_word));break;
        case (0xfb): CPU::EI();break;
        case (0xfe): CPU::CP(&working_byte);break;
        case (0xff): CPU::RST(0x38);break;
    }
}