#include "gb.h"

void Gameboy::decode() {
    switch (Gameboy::opcode) {
        // case (0x00): Gameboy::NOP();break; // There shouldn't be a need to call this
        case (0x01): Gameboy::LD(R.bc, &working_word);break;
        case (0x02): Gameboy::LD(mem_at(R.bc), R.a);break;
        case (0x03): Gameboy::INC(R.bc);break;
        case (0x04): Gameboy::INC(R.b);break;
        case (0x05): Gameboy::DEC(R.b);break;
        case (0x06): Gameboy::LD(R.b, &working_byte);break;
        case (0x07): Gameboy::RLC(R.a);break;
        case (0x08): Gameboy::LD16SP(working_byte);break;
        case (0x09): Gameboy::ADD(R.bc);break;
        case (0x0a): Gameboy::LD(R.a, mem_at(R.bc));break;
        case (0x0b): Gameboy::DEC(R.bc);break;
        case (0x0c): Gameboy::INC(R.c);break;
        case (0x0d): Gameboy::DEC(R.d);break;
        case (0x0e): Gameboy::LD(R.c, &working_byte);break;
        case (0x0f): Gameboy::RRC(R.a);break;
        case (0x10): Gameboy::STOP();break;
        case (0x11): Gameboy::LD(R.de, &working_word);break;
        case (0x12): Gameboy::LD(mem_at(R.de), R.a);break;
        case (0x13): Gameboy::INC(R.de);break;
        case (0x14): Gameboy::INC(R.d);break;
        case (0x15): Gameboy::DEC(R.d);break;
        case (0x16): Gameboy::LD(R.d, &working_byte);break;
        case (0x17): Gameboy::RL(R.a);break;
        case (0x18): Gameboy::JR((sbyte*) &working_byte);break;
        case (0x19): Gameboy::ADD(R.de);break;
        case (0x1a): Gameboy::LD(R.a, mem_at(R.de));break;
        case (0x1b): Gameboy::DEC(R.de);break;
        case (0x1c): Gameboy::INC(R.e);break;
        case (0x1d): Gameboy::DEC(R.e);break;
        case (0x1e): Gameboy::LD(R.e, &working_byte);break;
        case (0x1f): Gameboy::RRC(R.a);break;
        case (0x20): Gameboy::JRC(CC_NZ, (sbyte*) &working_byte);break;
        case (0x21): Gameboy::LD(R.hl, &working_word);break;
        case (0x22): Gameboy::LDI(mem_at(R.hl), R.a);break;
        case (0x23): Gameboy::INC(R.hl);break;
        case (0x24): Gameboy::INC(R.h);break;
        case (0x25): Gameboy::DEC(R.h);break;
        case (0x26): Gameboy::LD(R.h, &working_byte);break;
        case (0x27): Gameboy::DAA();break;
        case (0x28): Gameboy::JRC(CC_Z, (sbyte*) &working_byte);break;
        case (0x29): Gameboy::ADD(R.hl);break;
        case (0x2a): Gameboy::LDI(R.a, mem_at(R.hl));break;
        case (0x2b): Gameboy::DEC(R.hl);break;
        case (0x2c): Gameboy::INC(R.l);break;
        case (0x2d): Gameboy::DEC(R.l);break;
        case (0x2e): Gameboy::LD(R.l, &working_byte);break;
        case (0x2f): Gameboy::CPL();break;
        case (0x30): Gameboy::JRC(CC_NC, (sbyte*) &working_byte);break;
        case (0x31): Gameboy::LD(R.sp, &working_word);break;
        case (0x32): Gameboy::LDD(mem_at(R.hl), R.a);break;
        case (0x33): Gameboy::INC(R.sp);break;
        case (0x34): Gameboy::INC(mem_at(R.hl));break;
        case (0x35): Gameboy::DEC(mem_at(R.hl));break;
        case (0x36): Gameboy::LD(mem_at(R.hl), &working_byte);break;
        case (0x37): Gameboy::SCF();break;
        case (0x38): Gameboy::JRC(CC_C, (sbyte*) &working_byte);break;
        case (0x39): Gameboy::ADD(R.sp);break;
        case (0x3a): Gameboy::LDD(R.a, mem_at(R.hl));break;
        case (0x3b): Gameboy::DEC(R.sp);break;
        case (0x3c): Gameboy::INC(R.a);break;
        case (0x3d): Gameboy::DEC(R.a);break;
        case (0x3e): Gameboy::LD(R.a, &working_byte);break;
        case (0x3f): Gameboy::CCF();break;
        case (0x40): Gameboy::LD(R.b, R.b);break;
        case (0x41): Gameboy::LD(R.b, R.c);break;
        case (0x42): Gameboy::LD(R.b, R.d);break;
        case (0x43): Gameboy::LD(R.b, R.e);break;
        case (0x44): Gameboy::LD(R.b, R.h);break;
        case (0x45): Gameboy::LD(R.b, R.l);break;
        case (0x46): Gameboy::LD(R.b, mem_at(R.hl));break;
        case (0x47): Gameboy::LD(R.b, R.a);break;
        case (0x48): Gameboy::LD(R.c, R.b);break;
        case (0x49): Gameboy::LD(R.c, R.c);break;
        case (0x4a): Gameboy::LD(R.c, R.d);break;
        case (0x4b): Gameboy::LD(R.c, R.e);break;
        case (0x4c): Gameboy::LD(R.c, R.h);break;
        case (0x4d): Gameboy::LD(R.c, R.l);break;
        case (0x4e): Gameboy::LD(R.c, mem_at(R.hl));break;
        case (0x4f): Gameboy::LD(R.c, R.a);break;         
        case (0x50): Gameboy::LD(R.d, R.b);break;
        case (0x51): Gameboy::LD(R.d, R.c);break;
        case (0x52): Gameboy::LD(R.d, R.d);break;
        case (0x53): Gameboy::LD(R.d, R.e);break;
        case (0x54): Gameboy::LD(R.d, R.h);break;
        case (0x55): Gameboy::LD(R.d, R.l);break;
        case (0x56): Gameboy::LD(R.d, mem_at(R.hl));break;
        case (0x57): Gameboy::LD(R.d, R.a);break;         
        case (0x58): Gameboy::LD(R.e, R.b);break;
        case (0x59): Gameboy::LD(R.e, R.c);break;
        case (0x5a): Gameboy::LD(R.e, R.d);break;
        case (0x5b): Gameboy::LD(R.e, R.e);break;
        case (0x5c): Gameboy::LD(R.e, R.h);break;
        case (0x5d): Gameboy::LD(R.e, R.l);break;
        case (0x5e): Gameboy::LD(R.e, mem_at(R.hl));break;
        case (0x5f): Gameboy::LD(R.e, R.a);break;         
        case (0x60): Gameboy::LD(R.h, R.b);break;
        case (0x61): Gameboy::LD(R.h, R.c);break;
        case (0x62): Gameboy::LD(R.h, R.d);break;
        case (0x63): Gameboy::LD(R.h, R.e);break;
        case (0x64): Gameboy::LD(R.h, R.h);break;
        case (0x65): Gameboy::LD(R.h, R.l);break;
        case (0x66): Gameboy::LD(R.h, mem_at(R.hl));break;
        case (0x67): Gameboy::LD(R.h, R.a);break;         
        case (0x68): Gameboy::LD(R.l, R.b);break;
        case (0x69): Gameboy::LD(R.l, R.c);break;
        case (0x6a): Gameboy::LD(R.l, R.d);break;
        case (0x6b): Gameboy::LD(R.l, R.e);break;
        case (0x6c): Gameboy::LD(R.l, R.h);break;
        case (0x6d): Gameboy::LD(R.l, R.l);break;
        case (0x6e): Gameboy::LD(R.l, mem_at(R.hl));break;
        case (0x6f): Gameboy::LD(R.l, R.a);break;         
        case (0x70): Gameboy::LD(mem_at(R.hl), R.b);break;
        case (0x71): Gameboy::LD(mem_at(R.hl), R.c);break;
        case (0x72): Gameboy::LD(mem_at(R.hl), R.d);break;
        case (0x73): Gameboy::LD(mem_at(R.hl), R.e);break;
        case (0x74): Gameboy::LD(mem_at(R.hl), R.h);break;
        case (0x75): Gameboy::LD(mem_at(R.hl), R.l);break;
        case (0x76): Gameboy::HALT();break;
        case (0x77): Gameboy::LD(mem_at(R.hl), R.a);break;         
        case (0x78): Gameboy::LD(R.a, R.b);break;
        case (0x79): Gameboy::LD(R.a, R.c);break;
        case (0x7a): Gameboy::LD(R.a, R.d);break;
        case (0x7b): Gameboy::LD(R.a, R.e);break;
        case (0x7c): Gameboy::LD(R.a, R.h);break;
        case (0x7d): Gameboy::LD(R.a, R.l);break;
        case (0x7e): Gameboy::LD(R.a, mem_at(R.hl));break;
        case (0x7f): Gameboy::LD(R.a, R.a);break;         
        case (0x80): Gameboy::ADD(R.b);break;
        case (0x81): Gameboy::ADD(R.c);break;
        case (0x82): Gameboy::ADD(R.d);break;
        case (0x83): Gameboy::ADD(R.e);break;
        case (0x84): Gameboy::ADD(R.h);break;
        case (0x85): Gameboy::ADD(R.l);break;
        case (0x86): Gameboy::ADD(mem_at(R.hl));break;
        case (0x87): Gameboy::ADD(R.a);break;        
        case (0x88): Gameboy::ADC(R.b);break;
        case (0x89): Gameboy::ADC(R.c);break;
        case (0x8a): Gameboy::ADC(R.d);break;
        case (0x8b): Gameboy::ADC(R.e);break;
        case (0x8c): Gameboy::ADC(R.h);break;
        case (0x8d): Gameboy::ADC(R.l);break;
        case (0x8e): Gameboy::ADC(mem_at(R.hl));break;
        case (0x8f): Gameboy::ADC(R.a);break;
        case (0x90): Gameboy::SUB(R.b);break;
        case (0x91): Gameboy::SUB(R.c);break;
        case (0x92): Gameboy::SUB(R.d);break;
        case (0x93): Gameboy::SUB(R.e);break;
        case (0x94): Gameboy::SUB(R.h);break;
        case (0x95): Gameboy::SUB(R.l);break;
        case (0x96): Gameboy::SUB(mem_at(R.hl));break;
        case (0x97): Gameboy::SUB(R.a);break;        
        case (0x98): Gameboy::SBC(R.b);break;
        case (0x99): Gameboy::SBC(R.c);break;
        case (0x9a): Gameboy::SBC(R.d);break;
        case (0x9b): Gameboy::SBC(R.e);break;
        case (0x9c): Gameboy::SBC(R.h);break;
        case (0x9d): Gameboy::SBC(R.l);break;
        case (0x9e): Gameboy::SBC(mem_at(R.hl));break;
        case (0x9f): Gameboy::SBC(R.a);break;        
        case (0xa0): Gameboy::AND(R.b);break;
        case (0xa1): Gameboy::AND(R.c);break;
        case (0xa2): Gameboy::AND(R.d);break;
        case (0xa3): Gameboy::AND(R.e);break;
        case (0xa4): Gameboy::AND(R.h);break;
        case (0xa5): Gameboy::AND(R.l);break;
        case (0xa6): Gameboy::AND(mem_at(R.hl));break;
        case (0xa7): Gameboy::AND(R.a);break;        
        case (0xa8): Gameboy::XOR(R.b);break;
        case (0xa9): Gameboy::XOR(R.c);break;
        case (0xaa): Gameboy::XOR(R.d);break;
        case (0xab): Gameboy::XOR(R.e);break;
        case (0xac): Gameboy::XOR(R.h);break;
        case (0xad): Gameboy::XOR(R.l);break;
        case (0xae): Gameboy::XOR(mem_at(R.hl));break;
        case (0xaf): Gameboy::XOR(R.a);break;        
        case (0xb0): Gameboy::OR(R.b);break;
        case (0xb1): Gameboy::OR(R.c);break;
        case (0xb2): Gameboy::OR(R.d);break;
        case (0xb3): Gameboy::OR(R.e);break;
        case (0xb4): Gameboy::OR(R.h);break;
        case (0xb5): Gameboy::OR(R.l);break;
        case (0xb6): Gameboy::OR(mem_at(R.hl));break;
        case (0xb7): Gameboy::OR(R.a);break;        
        case (0xb8): Gameboy::CP(R.b);break;
        case (0xb9): Gameboy::CP(R.c);break;
        case (0xba): Gameboy::CP(R.d);break;
        case (0xbb): Gameboy::CP(R.e);break;
        case (0xbc): Gameboy::CP(R.h);break;
        case (0xbd): Gameboy::CP(R.l);break;
        case (0xbe): Gameboy::CP(mem_at(R.hl));break;
        case (0xbf): Gameboy::CP(R.a);break;        
        case (0xc0): Gameboy::RETC(CC_NZ);break;
        case (0xc1): Gameboy::POP(R.bc);break;
        case (0xc2): Gameboy::JPC(CC_NZ, &working_word);break;
        case (0xc3): Gameboy::JP(&working_word);break;
        case (0xc4): Gameboy::CALLC(CC_NZ, &working_word);break;
        case (0xc5): Gameboy::PUSH(R.bc);break;
        case (0xc6): Gameboy::ADD(&working_byte);break;
        case (0xc7): Gameboy::RST(0x00);break;
        case (0xc8): Gameboy::RETC(CC_Z);break;
        case (0xc9): Gameboy::RET();break;
        case (0xca): Gameboy::JPC(CC_Z, &working_word);break;
        case (0xcc): Gameboy::CALLC(CC_Z, &working_word);break;
        case (0xcd): Gameboy::CALL(&working_word);break;
        case (0xce): Gameboy::ADC(&working_byte);break;
        case (0xcf): Gameboy::RST(0x08);break;
        case (0xd0): Gameboy::RETC(CC_NC);break;
        case (0xd1): Gameboy::POP(R.de);break;
        case (0xd2): Gameboy::JPC(CC_NC, &working_word);break;
        case (0xd4): Gameboy::CALLC(CC_NC, &working_word);break;
        case (0xd5): Gameboy::PUSH(R.de);break;
        case (0xd6): Gameboy::SUB(&working_byte);break;
        case (0xd7): Gameboy::RST(0x10);break;
        case (0xd8): Gameboy::RETC(CC_C);break;
        case (0xd9): Gameboy::RETI();break;
        case (0xda): Gameboy::JPC(CC_C, &working_word);break;
        case (0xdc): Gameboy::CALLC(CC_C, &working_word);break;
        case (0xde): Gameboy::SBC(&working_byte);break;
        case (0xdf): Gameboy::RST(0x18);break;
        case (0xe0): Gameboy::LD(mem_at(0xFF00 + working_byte), R.a);break;
        case (0xe1): Gameboy::POP(R.hl);break;
        case (0xe2): Gameboy::LD(mem_at(0xFF00 + *R.c), R.a);break;
        case (0xe5): Gameboy::PUSH(R.hl);break;
        case (0xe6): Gameboy::AND(&working_byte);break;
        case (0xe7): Gameboy::RST(0x20);break;
        case (0xe8): Gameboy::ADD_SP((sbyte*) &working_byte);break;
        case (0xe9): Gameboy::JP(R.hl);break;
        case (0xea): Gameboy::LD(mem_at(working_word), R.a);break;
        case (0xee): Gameboy::XOR(&working_byte);break;
        case (0xef): Gameboy::RST(0x28);break;
        case (0xf0): Gameboy::LD(R.a, mem_at(0xFF00 + working_byte));break;
        case (0xf1): Gameboy::POP(R.af);break;
        case (0xf2): Gameboy::LD(R.a, mem_at(0xFF00 + *R.c));break;
        case (0xf3): Gameboy::DI();break;
        case (0xf5): Gameboy::PUSH(R.af);break;
        case (0xf6): Gameboy::OR(&working_byte);break;
        case (0xf7): Gameboy::RST(0x30);break;
        case (0xf8): Gameboy::LDHL();break;
        case (0xf9): Gameboy::LD(R.sp, R.hl);break;
        case (0xfa): Gameboy::LD(R.a, mem_at(working_word));break;
        case (0xfb): Gameboy::EI();break;
        case (0xfe): Gameboy::CP(&working_byte);break;
        case (0xff): Gameboy::RST(0x38);break;
    }
}