#include "gb.h"

void Gameboy::decode_prefixed() {
    switch (Gameboy::working_byte) {
        case (0x00): Gameboy::RLC(R.b); break;
        case (0x01): Gameboy::RLC(R.c); break;
        case (0x02): Gameboy::RLC(R.d); break;
        case (0x03): Gameboy::RLC(R.e); break;
        case (0x04): Gameboy::RLC(R.h); break;
        case (0x05): Gameboy::RLC(R.l); break;
        case (0x06): Gameboy::RLC(mem_at(R.hl)); break;
        case (0x07): Gameboy::RLC(R.a); break;
        case (0x08): Gameboy::RRC(R.b); break;
        case (0x09): Gameboy::RRC(R.c); break;
        case (0x0a): Gameboy::RRC(R.d); break;
        case (0x0b): Gameboy::RRC(R.e); break;
        case (0x0c): Gameboy::RRC(R.h); break;
        case (0x0d): Gameboy::RRC(R.l); break;
        case (0x0e): Gameboy::RRC(mem_at(R.hl)); break;
        case (0x0f): Gameboy::RRC(R.a); break;
        case (0x10): Gameboy::RL(R.b); break;
        case (0x11): Gameboy::RL(R.c); break;
        case (0x12): Gameboy::RL(R.d); break;
        case (0x13): Gameboy::RL(R.e); break;
        case (0x14): Gameboy::RL(R.h); break;
        case (0x15): Gameboy::RL(R.l); break;
        case (0x16): Gameboy::RL(mem_at(R.hl)); break;
        case (0x17): Gameboy::RL(R.a); break;
        case (0x18): Gameboy::RR(R.b); break;
        case (0x19): Gameboy::RR(R.c); break;
        case (0x1a): Gameboy::RR(R.d); break;
        case (0x1b): Gameboy::RR(R.e); break;
        case (0x1c): Gameboy::RR(R.h); break;
        case (0x1d): Gameboy::RR(R.l); break;
        case (0x1e): Gameboy::RR(mem_at(R.hl)); break;
        case (0x1f): Gameboy::RR(R.a); break;
        case (0x20): Gameboy::SLA(R.b); break;
        case (0x21): Gameboy::SLA(R.c); break;
        case (0x22): Gameboy::SLA(R.d); break;
        case (0x23): Gameboy::SLA(R.e); break;
        case (0x24): Gameboy::SLA(R.h); break;
        case (0x25): Gameboy::SLA(R.l); break;
        case (0x26): Gameboy::SLA(mem_at(R.hl)); break;
        case (0x27): Gameboy::SLA(R.a); break;
        case (0x28): Gameboy::SRA(R.b); break;
        case (0x29): Gameboy::SRA(R.c); break;
        case (0x2a): Gameboy::SRA(R.d); break;
        case (0x2b): Gameboy::SRA(R.e); break;
        case (0x2c): Gameboy::SRA(R.h); break;
        case (0x2d): Gameboy::SRA(R.l); break;
        case (0x2e): Gameboy::SRA(mem_at(R.hl)); break;
        case (0x2f): Gameboy::SRA(R.a); break;
        case (0x30): Gameboy::SWAP(R.b); break;
        case (0x31): Gameboy::SWAP(R.c); break;
        case (0x32): Gameboy::SWAP(R.d); break;
        case (0x33): Gameboy::SWAP(R.e); break;
        case (0x34): Gameboy::SWAP(R.h); break;
        case (0x35): Gameboy::SWAP(R.l); break;
        case (0x36): Gameboy::SWAP(mem_at(R.hl)); break;
        case (0x37): Gameboy::SWAP(R.a); break;
        case (0x38): Gameboy::SRL(R.b); break;
        case (0x39): Gameboy::SRL(R.c); break;
        case (0x3a): Gameboy::SRL(R.d); break;
        case (0x3b): Gameboy::SRL(R.e); break;
        case (0x3c): Gameboy::SRL(R.h); break;
        case (0x3d): Gameboy::SRL(R.l); break;
        case (0x3e): Gameboy::SRL(mem_at(R.hl)); break;
        case (0x3f): Gameboy::SRL(R.a); break;
        case (0x40): Gameboy::BIT(0, R.b); break;
        case (0x41): Gameboy::BIT(0, R.c); break;
        case (0x42): Gameboy::BIT(0, R.d); break;
        case (0x43): Gameboy::BIT(0, R.e); break;
        case (0x44): Gameboy::BIT(0, R.h); break;
        case (0x45): Gameboy::BIT(0, R.l); break;
        case (0x46): Gameboy::BIT(0, mem_at(R.hl)); break;
        case (0x47): Gameboy::BIT(0, R.a); break;
        case (0x48): Gameboy::BIT(1, R.b); break;
        case (0x49): Gameboy::BIT(1, R.c); break;
        case (0x4a): Gameboy::BIT(1, R.d); break;
        case (0x4b): Gameboy::BIT(1, R.e); break;
        case (0x4c): Gameboy::BIT(1, R.h); break;
        case (0x4d): Gameboy::BIT(1, R.l); break;
        case (0x4e): Gameboy::BIT(1, mem_at(R.hl)); break;
        case (0x4f): Gameboy::BIT(1, R.a); break;
        case (0x50): Gameboy::BIT(2, R.b); break;
        case (0x51): Gameboy::BIT(2, R.c); break;
        case (0x52): Gameboy::BIT(2, R.d); break;
        case (0x53): Gameboy::BIT(2, R.e); break;
        case (0x54): Gameboy::BIT(2, R.h); break;
        case (0x55): Gameboy::BIT(2, R.l); break;
        case (0x56): Gameboy::BIT(2, mem_at(R.hl)); break;
        case (0x57): Gameboy::BIT(2, R.a); break;
        case (0x58): Gameboy::BIT(3, R.b); break;
        case (0x59): Gameboy::BIT(3, R.c); break;
        case (0x5a): Gameboy::BIT(3, R.d); break;
        case (0x5b): Gameboy::BIT(3, R.e); break;
        case (0x5c): Gameboy::BIT(3, R.h); break;
        case (0x5d): Gameboy::BIT(3, R.l); break;
        case (0x5e): Gameboy::BIT(3, mem_at(R.hl)); break;
        case (0x5f): Gameboy::BIT(3, R.a); break;
        case (0x60): Gameboy::BIT(4, R.b); break;
        case (0x61): Gameboy::BIT(4, R.c); break;
        case (0x62): Gameboy::BIT(4, R.d); break;
        case (0x63): Gameboy::BIT(4, R.e); break;
        case (0x64): Gameboy::BIT(4, R.h); break;
        case (0x65): Gameboy::BIT(4, R.l); break;
        case (0x66): Gameboy::BIT(4, mem_at(R.hl)); break;
        case (0x67): Gameboy::BIT(4, R.a); break;
        case (0x68): Gameboy::BIT(5, R.b); break;
        case (0x69): Gameboy::BIT(5, R.c); break;
        case (0x6a): Gameboy::BIT(5, R.d); break;
        case (0x6b): Gameboy::BIT(5, R.e); break;
        case (0x6c): Gameboy::BIT(5, R.h); break;
        case (0x6d): Gameboy::BIT(5, R.l); break;
        case (0x6e): Gameboy::BIT(5, mem_at(R.hl)); break;
        case (0x6f): Gameboy::BIT(5, R.a); break;
        case (0x70): Gameboy::BIT(6, R.b); break;
        case (0x71): Gameboy::BIT(6, R.c); break;
        case (0x72): Gameboy::BIT(6, R.d); break;
        case (0x73): Gameboy::BIT(6, R.e); break;
        case (0x74): Gameboy::BIT(6, R.h); break;
        case (0x75): Gameboy::BIT(6, R.l); break;
        case (0x76): Gameboy::BIT(6, mem_at(R.hl)); break;
        case (0x77): Gameboy::BIT(6, R.a); break;
        case (0x78): Gameboy::BIT(7, R.b); break;
        case (0x79): Gameboy::BIT(7, R.c); break;
        case (0x7a): Gameboy::BIT(7, R.d); break;
        case (0x7b): Gameboy::BIT(7, R.e); break;
        case (0x7c): Gameboy::BIT(7, R.h); break;
        case (0x7d): Gameboy::BIT(7, R.l); break;
        case (0x7e): Gameboy::BIT(7, mem_at(R.hl)); break;
        case (0x7f): Gameboy::BIT(7, R.a); break;
        case (0x80): Gameboy::RES(0, R.b); break;
        case (0x81): Gameboy::RES(0, R.c); break;
        case (0x82): Gameboy::RES(0, R.d); break;
        case (0x83): Gameboy::RES(0, R.e); break;
        case (0x84): Gameboy::RES(0, R.h); break;
        case (0x85): Gameboy::RES(0, R.l); break;
        case (0x86): Gameboy::RES(0, mem_at(R.hl)); break;
        case (0x87): Gameboy::RES(0, R.a); break;
        case (0x88): Gameboy::RES(1, R.b); break;
        case (0x89): Gameboy::RES(1, R.c); break;
        case (0x8a): Gameboy::RES(1, R.d); break;
        case (0x8b): Gameboy::RES(1, R.e); break;
        case (0x8c): Gameboy::RES(1, R.h); break;
        case (0x8d): Gameboy::RES(1, R.l); break;
        case (0x8e): Gameboy::RES(1, mem_at(R.hl)); break;
        case (0x8f): Gameboy::RES(1, R.a); break;
        case (0x90): Gameboy::RES(2, R.b); break;
        case (0x91): Gameboy::RES(2, R.c); break;
        case (0x92): Gameboy::RES(2, R.d); break;
        case (0x93): Gameboy::RES(2, R.e); break;
        case (0x94): Gameboy::RES(2, R.h); break;
        case (0x95): Gameboy::RES(2, R.l); break;
        case (0x96): Gameboy::RES(2, mem_at(R.hl)); break;
        case (0x97): Gameboy::RES(2, R.a); break;
        case (0x98): Gameboy::RES(3, R.b); break;
        case (0x99): Gameboy::RES(3, R.c); break;
        case (0x9a): Gameboy::RES(3, R.d); break;
        case (0x9b): Gameboy::RES(3, R.e); break;
        case (0x9c): Gameboy::RES(3, R.h); break;
        case (0x9d): Gameboy::RES(3, R.l); break;
        case (0x9e): Gameboy::RES(3, mem_at(R.hl)); break;
        case (0x9f): Gameboy::RES(3, R.a); break;
        case (0xa0): Gameboy::RES(4, R.b); break;
        case (0xa1): Gameboy::RES(4, R.c); break;
        case (0xa2): Gameboy::RES(4, R.d); break;
        case (0xa3): Gameboy::RES(4, R.e); break;
        case (0xa4): Gameboy::RES(4, R.h); break;
        case (0xa5): Gameboy::RES(4, R.l); break;
        case (0xa6): Gameboy::RES(4, mem_at(R.hl)); break;
        case (0xa7): Gameboy::RES(4, R.a); break;
        case (0xa8): Gameboy::RES(5, R.b); break;
        case (0xa9): Gameboy::RES(5, R.c); break;
        case (0xaa): Gameboy::RES(5, R.d); break;
        case (0xab): Gameboy::RES(5, R.e); break;
        case (0xac): Gameboy::RES(5, R.h); break;
        case (0xad): Gameboy::RES(5, R.l); break;
        case (0xae): Gameboy::RES(5, mem_at(R.hl)); break;
        case (0xaf): Gameboy::RES(5, R.a); break;
        case (0xb0): Gameboy::RES(6, R.b); break;
        case (0xb1): Gameboy::RES(6, R.c); break;
        case (0xb2): Gameboy::RES(6, R.d); break;
        case (0xb3): Gameboy::RES(6, R.e); break;
        case (0xb4): Gameboy::RES(6, R.h); break;
        case (0xb5): Gameboy::RES(6, R.l); break;
        case (0xb6): Gameboy::RES(6, mem_at(R.hl)); break;
        case (0xb7): Gameboy::RES(6, R.a); break;
        case (0xb8): Gameboy::RES(7, R.b); break;
        case (0xb9): Gameboy::RES(7, R.c); break;
        case (0xba): Gameboy::RES(7, R.d); break;
        case (0xbb): Gameboy::RES(7, R.e); break;
        case (0xbc): Gameboy::RES(7, R.h); break;
        case (0xbd): Gameboy::RES(7, R.l); break;
        case (0xbe): Gameboy::RES(7, mem_at(R.hl)); break;
        case (0xbf): Gameboy::RES(7, R.a); break;
        case (0xc0): Gameboy::SET(0, R.b); break;
        case (0xc1): Gameboy::SET(0, R.c); break;
        case (0xc2): Gameboy::SET(0, R.d); break;
        case (0xc3): Gameboy::SET(0, R.e); break;
        case (0xc4): Gameboy::SET(0, R.h); break;
        case (0xc5): Gameboy::SET(0, R.l); break;
        case (0xc6): Gameboy::SET(0, mem_at(R.hl)); break;
        case (0xc7): Gameboy::SET(0, R.a); break;
        case (0xc8): Gameboy::SET(1, R.b); break;
        case (0xc9): Gameboy::SET(1, R.c); break;
        case (0xca): Gameboy::SET(1, R.d); break;
        case (0xcb): Gameboy::SET(1, R.e); break;
        case (0xcc): Gameboy::SET(1, R.h); break;
        case (0xcd): Gameboy::SET(1, R.l); break;
        case (0xce): Gameboy::SET(1, mem_at(R.hl)); break;
        case (0xcf): Gameboy::SET(1, R.a); break;
        case (0xd0): Gameboy::SET(2, R.b); break;
        case (0xd1): Gameboy::SET(2, R.c); break;
        case (0xd2): Gameboy::SET(2, R.d); break;
        case (0xd3): Gameboy::SET(2, R.e); break;
        case (0xd4): Gameboy::SET(2, R.h); break;
        case (0xd5): Gameboy::SET(2, R.l); break;
        case (0xd6): Gameboy::SET(2, mem_at(R.hl)); break;
        case (0xd7): Gameboy::SET(2, R.a); break;
        case (0xd8): Gameboy::SET(3, R.b); break;
        case (0xd9): Gameboy::SET(3, R.c); break;
        case (0xda): Gameboy::SET(3, R.d); break;
        case (0xdb): Gameboy::SET(3, R.e); break;
        case (0xdc): Gameboy::SET(3, R.h); break;
        case (0xdd): Gameboy::SET(3, R.l); break;
        case (0xde): Gameboy::SET(3, mem_at(R.hl)); break;
        case (0xdf): Gameboy::SET(3, R.a); break;
        case (0xe0): Gameboy::SET(4, R.b); break;
        case (0xe1): Gameboy::SET(4, R.c); break;
        case (0xe2): Gameboy::SET(4, R.d); break;
        case (0xe3): Gameboy::SET(4, R.e); break;
        case (0xe4): Gameboy::SET(4, R.h); break;
        case (0xe5): Gameboy::SET(4, R.l); break;
        case (0xe6): Gameboy::SET(4, mem_at(R.hl)); break;
        case (0xe7): Gameboy::SET(4, R.a); break;
        case (0xe8): Gameboy::SET(5, R.b); break;
        case (0xe9): Gameboy::SET(5, R.c); break;
        case (0xea): Gameboy::SET(5, R.d); break;
        case (0xeb): Gameboy::SET(5, R.e); break;
        case (0xec): Gameboy::SET(5, R.h); break;
        case (0xed): Gameboy::SET(5, R.l); break;
        case (0xee): Gameboy::SET(5, mem_at(R.hl)); break;
        case (0xef): Gameboy::SET(5, R.a); break;
        case (0xf0): Gameboy::SET(6, R.b); break;
        case (0xf1): Gameboy::SET(6, R.c); break;
        case (0xf2): Gameboy::SET(6, R.d); break;
        case (0xf3): Gameboy::SET(6, R.e); break;
        case (0xf4): Gameboy::SET(6, R.h); break;
        case (0xf5): Gameboy::SET(6, R.l); break;
        case (0xf6): Gameboy::SET(6, mem_at(R.hl)); break;
        case (0xf7): Gameboy::SET(6, R.a); break;
        case (0xf8): Gameboy::SET(7, R.b); break;
        case (0xf9): Gameboy::SET(7, R.c); break;
        case (0xfa): Gameboy::SET(7, R.d); break;
        case (0xfb): Gameboy::SET(7, R.e); break;
        case (0xfc): Gameboy::SET(7, R.h); break;
        case (0xfd): Gameboy::SET(7, R.l); break;
        case (0xfe): Gameboy::SET(7, mem_at(R.hl)); break;
        case (0xff): Gameboy::SET(7, R.a); break;
    }
}