#include "gb.h"

void Gameboy::step() {
    Gameboy::new_pc += Gameboy::fetch_instruction();
    switch (Gameboy::opcode) {
        // case (0x00): Gameboy::NOP();break;
        // case (0x01): Gameboy::LD();break;
        // case (0x02): Gameboy::LD();break;
        case (0x03): Gameboy::INC(registers.bc);break;
        case (0x04): Gameboy::INC(registers.b);break;
        // case (0x05): Gameboy::DEC();break;
        // case (0x06): Gameboy::LD();break;
        // case (0x07): Gameboy::RLCA();break;
        // case (0x08): Gameboy::LD();break;
        // case (0x09): Gameboy::ADD();break;
        // case (0x0a): Gameboy::LD();break;
        // case (0x0b): Gameboy::DEC();break;
        case (0x0c): Gameboy::INC(registers.c);break;
        // case (0x0d): Gameboy::DEC();break;
        // case (0x0e): Gameboy::LD();break;
        // case (0x0f): Gameboy::RRCA();break;
        // case (0x10): Gameboy::STOP();break;
        // case (0x11): Gameboy::LD();break;
        // case (0x12): Gameboy::LD();break;
        case (0x13): Gameboy::INC(registers.de);break;
        case (0x14): Gameboy::INC(registers.d);break;
        // case (0x15): Gameboy::DEC();break;
        // case (0x16): Gameboy::LD();break;
        // case (0x17): Gameboy::RLA();break;
        // case (0x18): Gameboy::JR();break;
        // case (0x19): Gameboy::ADD();break;
        // case (0x1a): Gameboy::LD();break;
        // case (0x1b): Gameboy::DEC();break;
        case (0x1c): Gameboy::INC(registers.e);break;
        // case (0x1d): Gameboy::DEC();break;
        // case (0x1e): Gameboy::LD();break;
        // case (0x1f): Gameboy::RRA();break;
        // case (0x20): Gameboy::JR();break;
        // case (0x21): Gameboy::LD();break;
        // case (0x22): Gameboy::LD();break;
        case (0x23): Gameboy::INC(registers.hl);break;
        case (0x24): Gameboy::INC(registers.h);break;
        // case (0x25): Gameboy::DEC();break;
        // case (0x26): Gameboy::LD();break;
        // case (0x27): Gameboy::DAA();break;
        // case (0x28): Gameboy::JR();break;
        // case (0x29): Gameboy::ADD();break;
        // case (0x2a): Gameboy::LD();break;
        // case (0x2b): Gameboy::DEC();break;
        case (0x2c): Gameboy::INC(registers.l);break;
        // case (0x2d): Gameboy::DEC();break;
        // case (0x2e): Gameboy::LD();break;
        // case (0x2f): Gameboy::CPL();break;
        // case (0x30): Gameboy::JR();break;
        // case (0x31): Gameboy::LD();break;
        // case (0x32): Gameboy::LD();break;
        case (0x33): Gameboy::INC(registers.sp);break;
        // case (0x34): Gameboy::INC();break;
        // case (0x35): Gameboy::DEC();break;
        // case (0x36): Gameboy::LD();break;
        // case (0x37): Gameboy::SCF();break;
        // case (0x38): Gameboy::JR();break;
        // case (0x39): Gameboy::ADD();break;
        // case (0x3a): Gameboy::LD();break;
        // case (0x3b): Gameboy::DEC();break;
        // case (0x3c): Gameboy::INC();break;
        // case (0x3d): Gameboy::DEC();break;
        // case (0x3e): Gameboy::LD();break;
        // case (0x3f): Gameboy::CCF();break;
        // case (0x40): Gameboy::LD();break;
        // case (0x41): Gameboy::LD();break;
        // case (0x42): Gameboy::LD();break;
        // case (0x43): Gameboy::LD();break;
        // case (0x44): Gameboy::LD();break;
        // case (0x45): Gameboy::LD();break;
        // case (0x46): Gameboy::LD();break;
        // case (0x47): Gameboy::LD();break;
        // case (0x48): Gameboy::LD();break;
        // case (0x49): Gameboy::LD();break;
        // case (0x4a): Gameboy::LD();break;
        // case (0x4b): Gameboy::LD();break;
        // case (0x4c): Gameboy::LD();break;
        // case (0x4d): Gameboy::LD();break;
        // case (0x4e): Gameboy::LD();break;
        // case (0x4f): Gameboy::LD();break;
        // case (0x50): Gameboy::LD();break;
        // case (0x51): Gameboy::LD();break;
        // case (0x52): Gameboy::LD();break;
        // case (0x53): Gameboy::LD();break;
        // case (0x54): Gameboy::LD();break;
        // case (0x55): Gameboy::LD();break;
        // case (0x56): Gameboy::LD();break;
        // case (0x57): Gameboy::LD();break;
        // case (0x58): Gameboy::LD();break;
        // case (0x59): Gameboy::LD();break;
        // case (0x5a): Gameboy::LD();break;
        // case (0x5b): Gameboy::LD();break;
        // case (0x5c): Gameboy::LD();break;
        // case (0x5d): Gameboy::LD();break;
        // case (0x5e): Gameboy::LD();break;
        // case (0x5f): Gameboy::LD();break;
        // case (0x60): Gameboy::LD();break;
        // case (0x61): Gameboy::LD();break;
        // case (0x62): Gameboy::LD();break;
        // case (0x63): Gameboy::LD();break;
        // case (0x64): Gameboy::LD();break;
        // case (0x65): Gameboy::LD();break;
        // case (0x66): Gameboy::LD();break;
        // case (0x67): Gameboy::LD();break;
        // case (0x68): Gameboy::LD();break;
        // case (0x69): Gameboy::LD();break;
        // case (0x6a): Gameboy::LD();break;
        // case (0x6b): Gameboy::LD();break;
        // case (0x6c): Gameboy::LD();break;
        // case (0x6d): Gameboy::LD();break;
        // case (0x6e): Gameboy::LD();break;
        // case (0x6f): Gameboy::LD();break;
        // case (0x70): Gameboy::LD();break;
        // case (0x71): Gameboy::LD();break;
        // case (0x72): Gameboy::LD();break;
        // case (0x73): Gameboy::LD();break;
        // case (0x74): Gameboy::LD();break;
        // case (0x75): Gameboy::LD();break;
        // case (0x76): Gameboy::HALT();break;
        // case (0x77): Gameboy::LD();break;
        // case (0x78): Gameboy::LD();break;
        // case (0x79): Gameboy::LD();break;
        // case (0x7a): Gameboy::LD();break;
        // case (0x7b): Gameboy::LD();break;
        // case (0x7c): Gameboy::LD();break;
        // case (0x7d): Gameboy::LD();break;
        // case (0x7e): Gameboy::LD();break;
        // case (0x7f): Gameboy::LD();break;
        // case (0x80): Gameboy::ADD();break;
        // case (0x81): Gameboy::ADD();break;
        // case (0x82): Gameboy::ADD();break;
        // case (0x83): Gameboy::ADD();break;
        // case (0x84): Gameboy::ADD();break;
        // case (0x85): Gameboy::ADD();break;
        // case (0x86): Gameboy::ADD();break;
        // case (0x87): Gameboy::ADD();break;
        case (0x88): Gameboy::ADC(registers.b);break;
        case (0x89): Gameboy::ADC(registers.c);break;
        case (0x8a): Gameboy::ADC(registers.d);break;
        case (0x8b): Gameboy::ADC(registers.e);break;
        case (0x8c): Gameboy::ADC(registers.h);break;
        case (0x8d): Gameboy::ADC(registers.l);break;
        case (0x8e): Gameboy::ADC(&mem[*registers.hl]);break;
        case (0x8f): Gameboy::ADC(registers.a);break;
        // case (0x90): Gameboy::SUB();break;
        // case (0x91): Gameboy::SUB();break;
        // case (0x92): Gameboy::SUB();break;
        // case (0x93): Gameboy::SUB();break;
        // case (0x94): Gameboy::SUB();break;
        // case (0x95): Gameboy::SUB();break;
        // case (0x96): Gameboy::SUB();break;
        // case (0x97): Gameboy::SUB();break;
        // case (0x98): Gameboy::SBC();break;
        // case (0x99): Gameboy::SBC();break;
        // case (0x9a): Gameboy::SBC();break;
        // case (0x9b): Gameboy::SBC();break;
        // case (0x9c): Gameboy::SBC();break;
        // case (0x9d): Gameboy::SBC();break;
        // case (0x9e): Gameboy::SBC();break;
        // case (0x9f): Gameboy::SBC();break;
        // case (0xa0): Gameboy::AND();break;
        // case (0xa1): Gameboy::AND();break;
        // case (0xa2): Gameboy::AND();break;
        // case (0xa3): Gameboy::AND();break;
        // case (0xa4): Gameboy::AND();break;
        // case (0xa5): Gameboy::AND();break;
        // case (0xa6): Gameboy::AND();break;
        // case (0xa7): Gameboy::AND();break;
        // case (0xa8): Gameboy::XOR();break;
        // case (0xa9): Gameboy::XOR();break;
        // case (0xaa): Gameboy::XOR();break;
        // case (0xab): Gameboy::XOR();break;
        // case (0xac): Gameboy::XOR();break;
        // case (0xad): Gameboy::XOR();break;
        // case (0xae): Gameboy::XOR();break;
        // case (0xaf): Gameboy::XOR();break;
        // case (0xb0): Gameboy::OR();break;
        // case (0xb1): Gameboy::OR();break;
        // case (0xb2): Gameboy::OR();break;
        // case (0xb3): Gameboy::OR();break;
        // case (0xb4): Gameboy::OR();break;
        // case (0xb5): Gameboy::OR();break;
        // case (0xb6): Gameboy::OR();break;
        // case (0xb7): Gameboy::OR();break;
        // case (0xb8): Gameboy::CP();break;
        // case (0xb9): Gameboy::CP();break;
        // case (0xba): Gameboy::CP();break;
        // case (0xbb): Gameboy::CP();break;
        // case (0xbc): Gameboy::CP();break;
        // case (0xbd): Gameboy::CP();break;
        // case (0xbe): Gameboy::CP();break;
        // case (0xbf): Gameboy::CP();break;
        // case (0xc0): Gameboy::RET();break;
        // case (0xc1): Gameboy::POP();break;
        // case (0xc2): Gameboy::JP();break;
        case (0xc3): Gameboy::JP(&working_word);break;
        // case (0xc4): Gameboy::CALL();break;
        // case (0xc5): Gameboy::PUSH();break;
        // case (0xc6): Gameboy::ADD();break;
        // case (0xc7): Gameboy::RST();break;
        // case (0xc8): Gameboy::RET();break;
        // case (0xc9): Gameboy::RET();break;
        // case (0xca): Gameboy::JP();break;
        // case (0xcb): Gameboy::PREFIX();break;
        // case (0xcc): Gameboy::CALL();break;
        // case (0xcd): Gameboy::CALL();break;
        case (0xce): Gameboy::ADC(&working_byte);break;
        // case (0xcf): Gameboy::RST();break;
        // case (0xd0): Gameboy::RET();break;
        // case (0xd1): Gameboy::POP();break;
        // case (0xd2): Gameboy::JP();break;
        // case (0xd4): Gameboy::CALL();break;
        // case (0xd5): Gameboy::PUSH();break;
        // case (0xd6): Gameboy::SUB();break;
        // case (0xd7): Gameboy::RST();break;
        // case (0xd8): Gameboy::RET();break;
        // case (0xd9): Gameboy::RETI();break;
        // case (0xda): Gameboy::JP();break;
        // case (0xdc): Gameboy::CALL();break;
        // case (0xde): Gameboy::SBC();break;
        // case (0xdf): Gameboy::RST();break;
        // case (0xe0): Gameboy::LDH();break;
        // case (0xe1): Gameboy::POP();break;
        // case (0xe2): Gameboy::LD();break;
        // case (0xe5): Gameboy::PUSH();break;
        // case (0xe6): Gameboy::AND();break;
        // case (0xe7): Gameboy::RST();break;
        // case (0xe8): Gameboy::ADD();break;
        // case (0xe9): Gameboy::JP();break;
        // case (0xea): Gameboy::LD();break;
        // case (0xee): Gameboy::XOR();break;
        // case (0xef): Gameboy::RST();break;
        // case (0xf0): Gameboy::LDH();break;
        // case (0xf1): Gameboy::POP();break;
        // case (0xf2): Gameboy::LD();break;
        // case (0xf3): Gameboy::DI();break;
        // case (0xf5): Gameboy::PUSH();break;
        // case (0xf6): Gameboy::OR();break;
        // case (0xf7): Gameboy::RST();break;
        // case (0xf8): Gameboy::LD();break;
        // case (0xf9): Gameboy::LD();break;
        // case (0xfa): Gameboy::LD();break;
        // case (0xfb): Gameboy::EI();break;
        // case (0xfe): Gameboy::CP();break;
        // case (0xff): Gameboy::RST();break;
    }
}